export const courses = [
  {
    idCourse: 1,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 5,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
  {
    idCourse: 2,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 4.5,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
  {
    idCourse: 3,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 3,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
  {
    idCourse: 4,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 5,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
  {
    idCourse: 5,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 5,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
  {
    idCourse: 6,
    nameCourse: "Fundamentals of Adobe XD Theory Learn New",
    courseImage: "/assets/image/course-image.jpg",
    price: 30,
    rating: 5,
    reviewAmount: 3,
    lessonAmount: 18,
    classType: "Online",
    author: "William Smmith",
    authorImage: "/assets/image/ava-author.jpg",
  },
];

export const filters = [
  {
    type: "categories",
    options: [
      "All Categories",
      "Uncategorized",
      "Academy",
      "Agency",
      "App",
      "Bar",
      "Blog",
      "Business",
      "Cafe",
      "College",
      "Construction",
      "Education",
    ],
  },
  {
    type: "languages",
    options: ["All Languages", "PHP", "JAVASCRIPT", "JAVA", "HTML", "PYTHON"],
  },
  {
    type: "prices",
    options: ["All Prices", ...Array.from({ length: 100 }, (_, i) => i + 1)],
  },
  {
    type: "skills",
    options: [
      "All Skills",
      "HTML",
      "CSS",
      "WORDPRESS",
      "JAVASCRIPT",
      "REACT",
      "ANGULAR",
      "VUE",
    ],
  },
];
